backend:
  name: git-gateway
  branch: source

publish_mode: editorial_workflow

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Post"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        hint: "This is the tile of the post that is shown on the website, keep it short but descriptive."
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        hint: "Set this date to whenever you started working on the post."
      - label: "Tags"
        name: "tags"
        widget: "list"
        hint: "This is to group a post specifically (e.g. osint, programming, linux, etc...). This should be a comma separated list."
        required: false
      - label: "Categories"
        name: "categories"
        widget: "list"
        default: ["sessions"]
        hint: "This is to group posts generally (e.g. events, sessions, etc...). This should be a comma separated list."
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"