---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: README.md
  label: Help
  read_only: true
- type: directory
  path: source/_posts
  label: Blog
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: directory
  path: source
  label: Pages
  create: all
  match: "**/*"
  exclude: "{_posts/**/*,*}"
  new_doc_ext: md
  templates:
  - page
upload_dir: source/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run preview
