name: Main Workflow
on: 
  push:
    branches:
    - source
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install
      uses: actions/npm@master
      with:
        args: install
    - name: Clean
      uses: heowc/action-hexo@master
      with:
        args: clean
    - name: Generate
      uses: heowc/action-hexo@master
      with:
        args: generate
    - name: Deploy to Github Pages
      uses: crazy-max/ghaction-github-pages@master
      with:
        target_branch: master
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
