name: Main Workflow
on: 
  push:
    branches:
    - source
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install
      run: npm install
    - name: Clean
      uses: heowc/action-hexo@master
      with:
        args: clean
    - name: Generate
      uses: heowc/action-hexo@master
      with:
        args: generate
    - name: Deploy to Github Pages
      uses: maxheld83/ghpages@v0.2.1
      env:
        GH_PAT: ${{ secrets.BOT_GITHUB_TOKEN }}
        BUILD_DIR: /github/workspace/public/
